#!/usr/bin/env python3

import os
import sys
import socket
import logging

FORMAT = '%(asctime)-15s %(message)s'
logging.basicConfig(format=FORMAT)
log = logging.getLogger(__name__)
  
def check(port: int) -> int:
  try:
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(("127.0.0.1", port))
    s.send(bytes("ruok", "utf-8"))
    data = s.recv(1024)
    s.close()
    imok = data == b"imok"
    if imok:
      return 0
    else:
      logging.error(f"Invalid status {data} returned from 127.0.0.1:{port}")
      return 1
  except Exception as ex:
    logging.error(f"Error checking status: {ex}")
    return 255


def main() -> int:
  return check(int(os.environ.get("ZK_CLIENT_PORT", "2181")))


if __name__ == "__main__":
  sys.exit(main())  
